---
###
# Set auth password
###
#
#	DESCRIPTION
#
#		Sets Redis Commander password
#
###
#
#	VARIABLES
#
#		parameter_redis_commander_auth_username - OPTIONAL-  Username to set
#		parameter_redis_commander_auth_password - OPTIONAL-  Password to set
#		parameter_redis_commander_auth_title    - OPTIONAL - Alternative descriptive title for actions taken
#
###
- name: "{{ parameter_add_bash_aliases_title | default('Setting up Redis Commander password') }}"
  template: src="../../templates/config/auth.j2"
            dest="{{ role_package_redis_commander__var__config_auth }}"
            force=true
  sudo: true

