---
- include: ../../../../logio/operations_logio/tasks/logio_configs/update_logio_harvester.yml
  vars:
    parameter_update_logio_harvester_title: Adding Pinba GUI site Nginx access logs to Log.io
    parameter_update_logio_harvester_name: Pinba GUI [{{ role_package_pinba_gui__var__port }}] (access)
    parameter_update_logio_harvester_files:
      - "{{ role_package_pinba_gui__var__logs_log }}"

- include: ../../../../logio/operations_logio/tasks/logio_configs/update_logio_harvester.yml
  vars:
    parameter_update_logio_harvester_title: Adding Pinba GUI site Nginx error logs to Log.io
    parameter_update_logio_harvester_name: Pinba GUI [{{ role_package_pinba_gui__var__port }}] (error)
    parameter_update_logio_harvester_files:
      - "{{ role_package_pinba_gui__var__logs_err }}"
