---
- include: ../../../../git/operations_git/tasks/git_repositories/git_repository_latest_version.yml
  vars:
    parameter_git_repository_latest_version_repo: "{{ role_package_kibana__var__repository_url }}"
    parameter_git_repository_latest_version_version_prefix: "v"
    parameter_git_repository_latest_version_title: "Getting latest Kibana version from Git"

- name: Setting found Kibana version
  set_fact:
    result_kibana_version: "{{ result_git_repository_latest_tag[1:] }}"

- include: ../../../../asset_downloads/operations_asset_downloads/tasks/download_dirs/create_assets_download_dirs.yml
  vars:
    parameter_create_assets_download_dirs: "{{ role_package_kibana__var__assets_dir }}"
    parameter_create_assets_download_dirs_prefix: ""
    parameter_create_assets_download_dirs_title: "Creating download dir for Kibana"

- name: Stopping Kibana if service exists
  service: name="{{ role_package_kibana__var__service }}"
           status=stopped
  failed_when: false
  sudo: true

- name: Removing old Kibana
  file: path="{{ role_package_kibana__var__kibana_dir }}"
        state="absent"
  sudo: true

- name: Creating Kibana directory
  file: path="{{ role_package_kibana__var__kibana_dir }}"
        state="directory"
        owner="root"
        group="root"
        mode="0755"
  sudo: true

- include: ../../../../asset_downloads/operations_asset_downloads/tasks/download/download_assets.yml
  vars:
    parameter_download_assets_title: "Downloading Kibana"
    parameter_download_assets_validate_certs: yes
    parameter_download_assets:
      - url: "https://download.elastic.co/kibana/kibana/kibana-{{ result_kibana_version }}-linux-{{ role_package_kibana__var__arhitecture[ ansible_architecture ].download_arhitecture }}.tar.gz"
        dest: "{{ role_package_kibana__var__assets_dir }}/{{ role_package_kibana__var__assets_download }}{{ result_kibana_version }}-{{ role_package_kibana__var__arhitecture[ ansible_architecture ].download_arhitecture }}.tar.gz"
        force: false
        extract_to: "{{ role_package_kibana__var__kibana_dir }}"
        extract_user: "root"
        extract_group: "root"

- name: Moving Kibana dir
  shell: "mv {{ role_package_kibana__var__kibana_dir }}/{{ item.from }} {{ role_package_kibana__var__kibana_dir }}/{{ item.to }}"
  sudo: true
  with_items:
    - from: "kibana-{{ result_kibana_version }}-linux-{{ role_package_kibana__var__arhitecture[ ansible_architecture ].download_arhitecture }}"
      to: "kibana"
