###
# Manage MySQL users
###
#
#	DESCRIPTION:
#
#		Manages specified MySQL users adding or removing them
#
###
#
#	VARIABLES:
#
#		parameter_manage_mysql_users[]               - REQUIRED - List of packages to manage
#		                                  .username  - REQUIRED - Login username
#		                                  .password  - OPTIONAL - Login password
#		                                  .priv      - OPTIONAL - Privilages to assign (if not *.*:ALL,GRANT)
#		                                  .host      - OPTIONAL - Host to assign (if not 127.0.0.1)
#		parameter_manage_mysql_users_state           - REQUIRED - State of users (absent, present)
#		parameter_manage_mysql_users_title           - OPTIONAL - Alternative descriptive title of action taken
#		parameter_manage_mysql_users_notify          - OPTIONAL - Notification to trigger if changes have been made
#
###
- name: "{{ parameter_manage_mysql_users_title | default('Managing MySQL users') }}"
  mysql_user: name="{{ item.username | mandatory }}"
              password="{% if item.password is defined %}{{ item.password }}{% endif %}"
              priv="{{ item.priv | default('*.*:ALL,GRANT') }}"
              host="{{ item.host | default('127.0.0.1') }}"
              append_privs=no
              state="{{ parameter_manage_mysql_users_state | mandatory }}"
              login_unix_socket="/var/run/mysqld/mysqld.sock"
  when: item.username != 'root'
  with_items: parameter_manage_mysql_users
  notify: "{{ parameter_manage_mysql_users_notify | default('Dummy MySQL operation notification') }}"
