---
- name: Building Go Lang
  shell: "./make.bash"
  args:
    chdir: "{{ role_package_go_lang__var__root }}/src"
  sudo: true
  sudo_user: root
  environment: "{{ role_package_go_lang__var__go_environment }}"
