###
# Manage Ruby gems
###
#
#	DESCRIPTION:
#
#		Manages specified Ruby games, installing them, updating them or removing them
#
###
#
#	VARIABLES:
#
#		parameter_manage_ruby_gems        - REQUIRED - List of gems to manage
#		parameter_manage_ruby_gems_state  - REQUIRED - State of package (latest, absent, present)
#		parameter_manage_ruby_gems_title  - OPTIONAL - Alternative descriptive title of action taken
#		parameter_manage_ruby_gems_notify - OPTIONAL - Notification to trigger if changes have been made
#
###

- name: "{{ parameter_manage_ruby_gems_title | default('Managing Ruby gems') }}"
  gem: name="{{ item[1] }}"
       include_dependencies=yes
       pre_release=no
       state="{{ parameter_manage_ruby_gems_state | mandatory }}"
       user_install=no
  sudo: true
  with_indexed_items: "{{ parameter_manage_ruby_gems }}"
  notify: "{{ parameter_manage_ruby_gems_notify | default('Dummy Ruby operation notification') }}"

