---
- include: ../../../../nodejs/operations_nodejs/tasks/nodejs_packages/install_nodejs_packages.yml
  vars:
    parameter_install_nodejs_packages_title: Installing Log.io
    parameter_install_nodejs_packages: "{{ role_package_logio__var__nodejs_packages }}"
  
