---
- include: ../../../../logio/operations_logio/tasks/logio_configs/update_logio_harvester.yml
  vars:
    parameter_update_logio_harvester_title: Adding Nginx access logs to Log.io
    parameter_update_logio_harvester_name: Nginx Access
    parameter_update_logio_harvester_files:
      - "/var/log/nginx/access.log"

- include: ../../../../logio/operations_logio/tasks/logio_configs/update_logio_harvester.yml
  vars:
    parameter_update_logio_harvester_title: Adding Nginx access logs to Log.io
    parameter_update_logio_harvester_name: Nginx Error
    parameter_update_logio_harvester_files:
      - "/var/log/nginx/error.log"
