###
# Backup MySQL databses
###
#
#	DESCRIPTION:
#
#		Backups specified MySQL databases
#
###
#
#	VARIABLES:
#
#		parameter_backup_mysql_databases[]              - REQUIRED - List of databases to backup
#		                                  .name         - REQUIRED - Database name
#		                                  .file         - REQUIRED - File location
#		                                  .force_backup - OPTIONAL - Set if database must exist and backup made
#		parameter_backup_mysql_databases_file_prefix    - OPTIONAL - File prefix for file locations
#		parameter_backup_mysql_databases_title          - OPTIONAL - Alternative descriptive title of action taken
#		parameter_backup_mysql_databases_notify         - OPTIONAL - Notification to trigger if changes have been made
#
###

- include: ./manage_mysql_databases.yml
  vars:
    parameter_manage_mysql_databases: "{{ parameter_backup_mysql_databases|mandatory }}"
    parameter_manage_mysql_databases_title: "{{ parameter_backup_mysql_databases_title | default('Backingup MySQL databases') }}"
    parameter_manage_mysql_databases_file_prefix: "{{ parameter_backup_mysql_databases_file_prefix|default('') }}"
    parameter_manage_mysql_databases_state: "dump"
    parameter_manage_mysql_databases_notify: "{{ parameter_backup_mysql_databases_noftify | default('Dummy MySQL operation notification') }}"
