###
# Create MySQL databses
###
#
#	DESCRIPTION:
#
#		Creates specified MySQL databases
#
###
#
#	VARIABLES:
#
#		parameter_create_mysql_databases[]           - REQUIRED - List of databases to create
#		                                  .name      - REQUIRED - Database name
#		                                  .collation - OPTIONAL - Collation used for database if not default
#		                                  .encoding  - OPTIONAL - Encoding used for database if not default
#		parameter_create_mysql_databases_title       - OPTIONAL - Alternative descriptive title of action taken
#		parameter_create_mysql_databases_notify      - OPTIONAL - Notification to trigger if changes have been made
#
###

- include: ./manage_mysql_databases.yml
  vars:
    parameter_manage_mysql_databases: "{{ parameter_create_mysql_databases|mandatory }}"
    parameter_manage_mysql_databases_title: "{{ parameter_create_mysql_databases_title | default('Creating MySQL databases') }}"
    parameter_manage_mysql_databases_state: "present"
    parameter_manage_mysql_databases_notify: "{{ parameter_create_mysql_databases_noftify | default('Dummy MySQL operation notification') }}"
