###
# Remove MySQL databses
###
#
#	DESCRIPTION:
#
#		Removes specified MySQL databases
#
###
#
#	VARIABLES:
#
#		parameter_remove_mysql_databases[]           - REQUIRED - List of databases to remove
#		                                  .name      - REQUIRED - Database name
#		parameter_remove_mysql_databases_title       - OPTIONAL - Alternative descriptive title of action taken
#		parameter_remove_mysql_databases_notify      - OPTIONAL - Notification to trigger if changes have been made
#
###

- include: ./manage_mysql_databases.yml
  vars:
    parameter_manage_mysql_databases: "{{ parameter_remove_mysql_databases|mandatory }}"
    parameter_manage_mysql_databases_title: "{{ parameter_remove_mysql_databases_title | default('Removing MySQL databases') }}"
    parameter_manage_mysql_databases_state: "absent"
    parameter_manage_mysql_databases_notify: "{{ parameter_remove_mysql_databases_noftify | default('Dummy MySQL operation notification') }}"
