---
- include: ../../../../logio/operations_logio/tasks/logio_configs/update_logio_harvester.yml
  vars:
    parameter_update_logio_harvester_title: Adding MySQL logs to Log.io
    parameter_update_logio_harvester_name: MySQL
    parameter_update_logio_harvester_files:
      - "/var/log/mysql.log"

- include: ../../../../logio/operations_logio/tasks/logio_configs/update_logio_harvester.yml
  vars:
    parameter_update_logio_harvester_title: Adding MySQL error logs to Log.io
    parameter_update_logio_harvester_name: MySQL (error)
    parameter_update_logio_harvester_files:
      - /var/log/mysql.err
      - /var/log/mysql/error.log
