---
- name: "Getting assets dir user"
  shell: "stat '{{ role_support_vagrant_assets__setup__path | mandatory }}' --format=%U"
  sudo: true
  changed_when: false
  register: result_assets_dir_user

- name: "Getting assets dir group"
  shell: "stat '{{ role_support_vagrant_assets__setup__path | mandatory }}' --format=%G"
  sudo: true
  changed_when: false
  register: result_assets_dir_group

- name: "Setting up assets dir facts"
  set_fact:
    fact_assets_dir_path: "{{ role_support_vagrant_assets__setup__path | mandatory }}"    
    fact_assets_dir_user: "{{ result_assets_dir_user.stdout | mandatory }}"
    fact_assets_dir_group: "{{ result_assets_dir_group.stdout | mandatory }}"
