###
# Manage Node.js Packages
###
#
#	DESCRIPTION:
#
#		Manages specified Node.js packages, installing them, updating them or removing them
#
###
#
#	VARIABLES:
#
#		parameter_manage_nodejs_packages        - REQUIRED - List of packages to manage
#		parameter_manage_nodejs_packages_state  - REQUIRED - State of package (latest, absent, present)
#		parameter_manage_nodejs_packages_title  - OPTIONAL - Alternative descriptive title of action taken
#		parameter_manage_nodejs_packages_notify - OPTIONAL - Notification to trigger if changes have been made
#
###

- name: "{{ parameter_manage_nodejs_packages_title | default('Managing Node.js Packages') }}"
  npm: name="{{ item[1] }}"
       production=yes
       state="{{ parameter_manage_nodejs_packages_state | mandatory }}"
       global=yes
       ignore_scripts=no
  sudo: true
  with_indexed_items: "{{ parameter_manage_nodejs_packages }}"
  notify: "{{ parameter_manage_nodejs_packages_notify | default('Dummy Node.js operation notification') }}"

