---
- include: ../../../../logio/operations_logio/tasks/logio_configs/update_logio_harvester.yml
  vars:
    parameter_update_logio_harvester_title: Adding PhpMyAdmin site Nginx access logs to Log.io
    parameter_update_logio_harvester_name: PhpMyAdmin [{{ role_nginx_phpmyadmin__var__port }}] (access)
    parameter_update_logio_harvester_files:
      - "{{ role_nginx_phpmyadmin__var__logs_log }}"

- include: ../../../../logio/operations_logio/tasks/logio_configs/update_logio_harvester.yml
  vars:
    parameter_update_logio_harvester_title: Adding PhpMyAdmin site Nginx error logs to Log.io
    parameter_update_logio_harvester_name: PhpMyAdmin [{{ role_nginx_phpmyadmin__var__port }}] (error)
    parameter_update_logio_harvester_files:
      - "{{ role_nginx_phpmyadmin__var__logs_err }}"
