---
role_support_dev_site__setup__nginx_http_port: 80
role_support_dev_site__setup__nginx_server_name: localhost
role_support_dev_site__setup__nginx_fpm_error_log_string: dev_site_nginx
role_support_dev_site__setup__fpm_listen: 127.0.0.1:9001
role_support_dev_site__setup__path: /opt/dev-site/
role_support_dev_site__setup__source_path: "{{ role_support_dev_site__setup__path }}/source"
role_support_dev_site__setup__nginx_path: "{{ role_support_dev_site__setup__path }}/nginx_include"
role_support_dev_site__setup__web_path: "{{ role_support_dev_site__setup__source_path }}/web"
role_support_dev_site__setup__logs_path: "{{ role_support_dev_site__setup__path }}/logs"

role_support_dev_site__setup__bash_aliases:
  - name: goto-dev-site
    command: cd {{ role_support_dev_site__setup__source_path }}

