---
- name: Checking if Go Lang 1.4 is built
  stat: path="{{ role_package_go_lang_1_4__var__root }}/bin/go"
  sudo: true
  register: result_go_lang_1_4_built
  
- name: Building Go Lang 1.4
  shell: "./make.bash"
  args:
    chdir: "{{ role_package_go_lang_1_4__var__root }}/src"
  sudo: true
  sudo_user: root
  environment: "{{ role_package_go_lang_1_4__var__go_environment }}"
  when: not(result_go_lang_1_4_built.stat.exists) or result_git_checkout.changed
