---
- include: ../../../../vagrant_assets/operations_vagrant_assets/tasks/assets_dirs/create_assets_dirs.yml
  vars:
    parameter_create_assets_dirs: "{{ role_actions_mysql__var__mysql_assets_dir }}"
    parameter_create_assets_dirs_title: Creating assets dir for MySQL backups
