- include: ../../../operations_mysql/tasks/mysql_databases/cycle_mysql_databases.yml
  vars:
    parameter_cycle_mysql_databases_title: "Cycling user specified MySQL databases (from assets)"
    parameter_cycle_mysql_databases: "{{ role_actions_mysql__tasks__cycle_mysql_assets_databases__databases }}"
    parameter_cycle_mysql_databases_file_prefix: "{{ fact_assets_dir_path }}/{{ role_actions_mysql__var__mysql_assets_dir }}/"
