- include: ../../../operations_mysql/tasks/mysql_config/set_mysql_bind_address.yml
  vars:
    parameter_set_mysql_bind_address_title: "Setting User specified MySQL bind address"
    parameter_set_mysql_bind_address: "{{ role_actions_mysql__tasks__set_mysql_bind_address__address }}"
