---
- include: ../../../../git/operations_git/tasks/git_repositories/git_repositories_checkout.yml
  vars:
    parameter_checkout_git_repositories_title: Downloading Cloud 9
    parameter_checkout_git_repositories:
      - repo: "{{ role_package_cloud9__var__git_repository }}"
        dest:  "{{ role_package_cloud9__var__location }}"
        version: master
        accept_hostkey: true
        clone: true
        force: true
        recursive: true
        update: true
        user: "{{ role_package_cloud9__var__user }}"
        group: "{{ role_package_cloud9__var__group }}"
        folder_mode: 755

- name: Installing Cloud 9
  shell: "sudo -u {{ role_package_cloud9__var__user }} -H  {{ item }}"
  args:
    chdir: "{{ role_package_cloud9__var__location }}"
  sudo: true
  sudo_user: "{{ role_package_cloud9__var__user }}"
  with_items:
    - scripts/install-sdk.sh
#    - build/build-standalone.sh

- include: ../../../../nodejs/operations_nodejs/tasks/nodejs_packages/install_nodejs_packages.yml
  vars:
    parameter_install_nodejs_packages:
      - debug
    parameter_install_nodejs_packages_title: Installing additional NodeJs packages for Cloud 9
    parameter_install_nodejs_packages_latest: true
