---
- name: Building Pinba
  shell: "{{ item }}"
  args:
    chdir: "{{ role_package_pinba__var__root }}"
  sudo: true
  sudo_user: root
  with_items:
    - ./buildconf.sh
    - "./configure --with-mysql={{ fact_mysql_source.location }} --libdir={{ fact_mysql.plugin_dir }}"
    - make install