---
- include: ../../../../logio/operations_logio/tasks/logio_configs/update_logio_harvester.yml
  vars:
    parameter_update_logio_harvester_title: Adding ElasticSearch logs to Log.io
    parameter_update_logio_harvester_name: ElasticSearch
    parameter_update_logio_harvester_files:
      - "/var/log/elasticsearch/elasticsearch.log"

- include: ../../../../logio/operations_logio/tasks/logio_configs/update_logio_harvester.yml
  vars:
    parameter_update_logio_harvester_title: Adding ElasticSearch error logs to Log.io
    parameter_update_logio_harvester_name: ElasticSearch indexing slow
    parameter_update_logio_harvester_files:
      - "/var/log/elasticsearch/elasticsearch_index_indexing_slowlog.log"

- include: ../../../../logio/operations_logio/tasks/logio_configs/update_logio_harvester.yml
  vars:
    parameter_update_logio_harvester_title: Adding ElasticSearch error logs to Log.io
    parameter_update_logio_harvester_name: ElasticSearch searching slow
    parameter_update_logio_harvester_files:
      - "/var/log/elasticsearch/elasticsearch_index_search_slowlog.log"
