###
# Add Apt Repositories
###
#
#	DESCRIPTION:
#
#		Adds specified Apt repositories
#
###
#
#	VARIABLES:
#
#		parameter_add_apt_repositories                - REQUIRED - List of repositories to add
#		parameter_add_apt_repositories_update_cache   - REQUIRED - Should caches be updated upon changes
#		parameter_add_apt_repositories_title          - OPTIONAL - Alternative descriptive title of action taken
#               parameter_add_apt_repositories_valdate_certs  - OPTIONAL - Should SSL certificates of target repos be validated
#		parameter_add_apt_repositories_notify         - OPTIONAL - Notification to trigger if changes have been made
###

- include: ./manage_apt_repositories.yml
  vars:
    parameter_manage_apt_repositories: "{{ parameter_add_apt_repositories | mandatory }}"
    parameter_manage_apt_repositories_update_cache: "{{ parameter_add_apt_repositories_update_cache | mandatory }}"
    parameter_manage_apt_repositories_state: "present"
    parameter_manage_apt_repositories_title: "{{ parameter_add_apt_repositories_title | default('Adding APT repositories') }}"
    parameter_manage_apt_repositories_validate_certs: "{{ parameter_add_apt_repositories_validate_certs | default( task_default__operations_apt__apt_repositories__manage_apt_repositories__validate_certs ) }}"
    parameter_manage_apt_repositories_notify: "{{ parameter_add_apt_repositories_notify | default('Dummy APT operation notification') }}" 
