---
- include: ../../../../apt/operations_apt/tasks/apt_packages/install_apt_packages.yml
  vars:
    parameter_install_apt_packages_title: Installing International Components for Unicode library
    parameter_install_apt_packages: "{{ role_package_php5_intl__var__apt_packages }}"

- include: ../../../../php5/operations_php5/tasks/php5_modules/install_php5_modules.yml
  vars:
    parameter_install_php5_modules_title: Installing Intl PHP module
    parameter_install_php5_modules: "{{ role_package_php5_intl__var__php5_modules_install }}"

- include: ../../../../php5/operations_php5/tasks/php5_modules/enable_php5_modules.yml
  vars:
    parameter_enable_php5_modules_title: Enabling Intl PHP module
    parameter_enable_php5_modules: "{{ role_package_php5_intl__var__php5_modules_enable }}"
  
