## Task default variables ##

task_default__operations_apt__apt_packages__manage_apt_packages__force: yes
task_default__operations_apt__apt_packages__manage_apt_packages__install_recommends: no
task_default__operations_apt__apt_packages__manage_apt_packages__purge: yes

task_default__operations_apt__apt_packages__install_apt_packages__latest: yes
task_default__operations_apt__apt_packages__install_apt_packages__force: "{{ task_default__operations_apt__apt_packages__manage_apt_packages__force }}"
task_default__operations_apt__apt_packages__install_apt_packages__install_recommends: "{{ task_default__operations_apt__apt_packages__manage_apt_packages__install_recommends }}"

task_default__operations_apt__apt_packages__remove_apt_packages__force: "{{ task_default__operations_apt__apt_packages__manage_apt_packages__force }}"
task_default__operations_apt__apt_packages__remove_apt_packages__purge: "{{ task_default__operations_apt__apt_packages__manage_apt_packages__purge }}"

task_default__operations_apt__apt_repositories__manage_apt_repositories__validate_certs: yes

task_default__operations_apt__apt_repositories__add_apt_repositories__validate_certs: "{{ task_default__operations_apt__apt_repositories__manage_apt_repositories__validate_certs }}"

task_default__operations_apt__apt_keys__download_apt_keys__validate_certs: yes
