###
#  Php 5 fpm pool
###
#
#    DESCRIPTION:
#
#        Configures Php 5 Fpm service pool
#
###
#
#    VARIABLES:
#
#        parameter_php5_fpm_pool[]                  - REQUIRED - Configuration for FPM www pool
#                                 .section          - OPTIONAL - Name of subsection in ini file if different then module name
#                                 .content[]        - REQUIRED - Content of configuration
#                                          .option - REQUIRED - Option name
#                                          .value  - REQUIRED - Option value
#       parameter_php5_fpm_pool_name               - REQUURED - Pool name
#        parameter_php5_fpm_pool_title              - OPTIONAL - Alternative title for actions taken
#        parameter_php5_fpm_pool_notify             - OPTIONAL - Notifications to trigger if anything has changed
#
###
---
- name: "{{ parameter_php5_fpm_pool_title | default('Updating Php 5 pool configuration') }} (Ensuring PHP 5 Fpm pool file exists)"
  file: path="{{ role_package_php5__var__fpm_pool_dir }}/{{ parameter_php5_fpm_pool_name | mandatory }}.conf"
        owner="root"
        group="root"
        state="touch"
  sudo: true
  
- include: ../../../../ini_files/operations_ini_files/tasks/ini_files/update_ini_files.yml
  vars:
    parameter_update_ini_file: "{{ role_package_php5__var__fpm_pool_dir }}/{{ parameter_php5_fpm_pool_name | mandatory }}.conf"
    parameter_update_ini_file_content: "{{ parameter_php5_fpm_pool }}"
    parameter_update_ini_file_title: "{{ parameter_php5_fpm_pool_title | default('Updating Php 5 pool configuration') }}"
    parameter_update_ini_file_notify: "{{ parameter_php5_fpm_pool_notify | default ('Dummy Php 5 operation notification') }}"
    parameter_update_ini_file_default_section: "{{ parameter_php5_fpm_pool_name | mandatory }}"
