---
- include: ../../../../php5/operations_php5/tasks/php5_modules/config_php5_module.yml
  vars:
    parameter_config_php5_module_title: Creating Php 5 MailHog Sendmail module config
    parameter_config_php5_module: mailhog
    parameter_config_php5_module_create_if_not_existing: yes
    parameter_config_php5_module_config:
      - content:
          - option: sendmail_path
            value: "'{{ role_package_go_lang__var__path }}/bin/mhsendmail --smtp-addr={% if role_package_mailhog__config__smtp_server__host == '0.0.0.0' %}127.0.0.1{% else %}{{ role_package_mailhog__config__smtp_server__host }}{% endif %}:{{ role_package_mailhog__config__smtp_server__port }} to@mailhog'"

- include: ../../../../php5/operations_php5/tasks/php5_modules/enable_php5_modules.yml
  vars:
    parameter_enable_php5_modules_title: Enabling Php 5 MailHog module config
    parameter_enable_php5_modules:
      - mailhog
