###
# Config Php 5 module
###
#
#	DESCRIPTION:
#
#		Updates Php 5 ini
#
###
#
#	VARIABLES:
#
#		parameter_php5_ini[]                  - REQUIRED - Configuration for module
#		                    .section          - OPTIONAL - Name of subsection in ini file if different then module name
#		                    .content[]        - REQUIRED - Content of configuration
#                                     .option         - REQUIRED - Option name
#                                     .value          - REQUIRED - Option value
#		parameter_php5_ini_cli		      - OPTIONAL - Should CLI configuration be handled
#		parameter_php5_ini_fpm                - OPTIONAL - Should FPM configuration be handled
#		parameter_php5_ini_title              - OPTIONAL - Alternative title for actions taken
#		parameter_php5_ini_notify             - OPTIONAL - Notifications to trigger if anything has changed
#
###
---
- include: ../../../../ini_files/operations_ini_files/tasks/ini_files/update_ini_files.yml
  vars:
    parameter_update_ini_file: "{{ role_package_php5__var__fpm_ini }}"
    parameter_update_ini_file_content: "{{ parameter_php5_ini }}"
    parameter_update_ini_file_title: "{{ parameter_php5_ini_title | default('Updating Php 5 configuration') }} (Updating Php 5 FPM)"
    parameter_update_ini_file_notify: "{{ parameter_php5_ini_notify | default ('Dummy Php 5 operation notification') }}"
    parameter_update_ini_file_default_section: "PHP"
  when: parameter_php5_ini_fpm | default( true )
  
- include: ../../../../ini_files/operations_ini_files/tasks/ini_files/update_ini_files.yml
  vars:
    parameter_update_ini_file: "{{ role_package_php5__var__cli_ini }}"
    parameter_update_ini_file_content: "{{ parameter_php5_ini }}"
    parameter_update_ini_file_title: "{{ parameter_php5_ini_title | default('Updating Php 5 configuration') }} (Updating Php 5 CLI)"
    parameter_update_ini_file_notify: "{{ parameter_php5_ini_notify | default ('Dummy Php 5 operation notification') }}"
    parameter_update_ini_file_default_section: "PHP"
  when: parameter_php5_ini_cli | default( true )
