---
- include: ../../../../php5/operations_php5/tasks/php5_modules/install_php5_modules.yml
  vars:
    parameter_install_php5_modules_title: Installing Php5 modules for Smyfony2
    parameter_install_php5_modules: "{{ role_package_smyfony2__var__php5_modules_install }}"

- include: ../../../../php5/operations_php5/tasks/php5_modules/enable_php5_modules.yml
  vars:
    parameter_enable_php5_modules_title: Enabling Php5 modules for Smyfony2
    parameter_enable_php5_modules: "{{ role_package_smyfony2__var__php5_modules_enable }}"

- include: ../../../../php5/operations_php5/tasks/php5_ini/php5_ini.yml
  vars:
    parameter_php5_ini_title: Configuring PHP 5 ini files
    parameter_php5_ini_cli: true
    parameter_php5_ini_fpm: true
    parameter_php5_ini:
      - section: PHP
        content:
          - option: short_open_tag
            value: "Off"
          - option: magic_quotes_gpc
            value: "Off"
          - option: register_globals
            value: "Off"
          - option: session.auto_start
            value: "Off"
          - option: date.timezone
            value: "UTC"
