---
###
# Adds /usr/local/bin scripts from templates
###
#
#	DESCRIPTION:
#
#		Adds /usr/local/bin scripts from templates
###
#
#	VARIABLES:
#
#		parameter_add_usr_bin_templates_dir          - REQUIRED - Dir with /usr/local/bin templates
#		parameter_add_usr_bin_templates_title        - OPTIONAL - Alternative descriptive title of what is being done
#
###
- name: "{{ parameter_add_usr_bin_templates_title | default('Adding /usr/local/bin scripts') }} (Copying files to users bin directory)"
  template: src="{{ item }}"
            dest="{{ fact_user_environment_user_home_dir }}/{{ role_support_user_environment__setup__usr_local_bin }}/{{ item[:(item|length-3)]|basename }}"
            owner="{{ fact_user_environment_user_home_dir_user }}"
            group="{{ fact_user_environment_user_home_dir_group }}"
            mode=755
  with_fileglob:
    - "{{ parameter_add_usr_bin_templates_dir | mandatory }}/*.j2"
  sudo: true

- name: "{{ parameter_add_usr_bin_templates_title | default('Adding /usr/local/bin scripts') }} (Linking files to /usr/local/bin directory)"
  file: src="{{ fact_user_environment_user_home_dir }}/{{ role_support_user_environment__setup__usr_local_bin }}/{{ item[:(item|length-3)]|basename }}"
        dest="/usr/local/bin/{{ item[:(item|length-3)]|basename }}"
        state="link"
  sudo: yes
  with_fileglob:
    - "{{ parameter_add_usr_bin_templates_dir | mandatory }}/*.j2"
