###
# Manage Python PIP Packages
###
#
#	DESCRIPTION:
#
#		Manages specified Python PIP packages, installing them, updating them or removing them
#
###
#
#	VARIABLES:
#
#		parameter_manage_pip_packages        - REQUIRED - List of packages to manage
#		parameter_manage_pip_packages_state  - REQUIRED - State of package (latest, absent, present)
#		parameter_manage_pip_packages_title  - OPTIONAL - Alternative descriptive title of action taken
#		parameter_manage_pip_packages_notify - OPTIONAL - Notification to trigger if changes have been made
#
###

- name: "{{ parameter_manage_pip_packages_title | default('Managing Node.js Packages') }}"
  pip: name="{{ item[1] }}"
       state="{{ parameter_manage_pip_packages_state | mandatory }}"
  sudo: true
  with_indexed_items: "{{ parameter_manage_pip_packages }}"
  notify: "{{ parameter_manage_pip_packages_notify | default('Dummy Python PIP operation notification') }}"

