---
- name: Starting Redis
  service: name="{{ item }}"
           sleep="2"
           state="restarted"
  with_items:
    - "{{ role_package_redis__var__service }}"
  sudo: true

- name: Stopping Redis and scheduling restart
  service: name="{{ item }}"
           state="stopped"
  with_items:
    - "{{ role_package_redis__var__service }}"
  changed_when: true
  notify: Restart Redis
  sudo: true
