---
###
# Enable Nginx websites
###
#	DESCRIPTION:
#
#		Enables nginx websites
###
#
#	VARIABLES:
#
#		parameter_enable_nginx_sites        - REQUIRED - List of Nginx websites to enable
#		parameter_enable_nginx_sites_title  - OPTIONAL - Alternative descriptive title of what is being done
#		parameter_enable_nginx_sites_notify - OPTIONAL - Notification to be triggered on any changes made
###
- name: "{{ parameter_enable_nginx_sites_title | default('Enabling Nginx website configurations') }}"
  file: src={{ fact_nginx_sites_available_dir ~ '/' ~ item }}
        path="{{ fact_nginx_sites_enabled_dir }}/{{ (item|basename) }}"
        owner="{{ fact_nginx_sites_enabled_dir_user }}"
        group="{{ fact_nginx_sites_enabled_dir_group }}"
        state=link
  with_items: parameter_enable_nginx_sites
  sudo: true
  notify: "{{ parameter_enable_nginx_sites_notify | default('Dummy Nginx operation notification') }}"
