---
###
# Remove Nginx websites
###
#	DESCRIPTION:
#
#		Removes Nginx websites
###
#
#	VARIABLES:
#
#		parameter_disable_nginx_sites        - REQUIRED - List of Nginx websites to disable
#		parameter_disable_nginx_sites_title  - OPTIONAL - Alternative descriptive title of what is being done
#		parameter_disable_nginx_sites_notify - OPTIONAL - Notification to be triggered on any changes made
###
- include: ./disable_nginx_websites.yml
  vars:
    parameter_disable_nginx_sites_title: "{{ parameter_remove_nginx_sites | default('Preparing to remove Nginx sites') }} (Disabling Nginx sites before removal)"
    parameter_disable_nginx_sites: "{{ parameter_remove_nginx_sites | mandatory }}"
    parameter_disable_nginx_sites_notify: "{{ parameter_remove_nginx_sites_notify | default('Dummy Nginx operation notification') }}"

- name: "{{ parameter_remove_nginx_sites_title | default('Removing Nginx website configurations') }}"
  file: path="{{ fact_nginx_sites_available_dir }}/{{ (item|basename) }}"
        state=absent
  with_items: parameter_disable_nginx_sites
  sudo: true
  notify: "{{ parameter_disable_nginx_sites_notify | default('Dummy Nginx operation notification') }}"
