---
###
# Remove auth passwords
###
#
#	DESCRIPTION
#
#		Removes MailHog Auth passwords
#
###
#
#	VARIABLES
#
#		parameter_mailhog_remove_auth_title      - OPTIONAL - Alternative descriptive title for actions taken
#
###
- name: "{{ parameter_mailhog_remove_auth_title | default('Removing MaihHog Passwords') }}"
  lineinfile: dest="{{ role_package_mailhog__var__config_auth }}"
              regexp="$"
              state=absent
  sudo: true
