---
###
# Set auth password
###
#
#	DESCRIPTION
#
#		Sets MailHog Auth passwords
#
###
#
#	VARIABLES
#
#		parameter_mailhog_auth[]          - REQUIRED - List of passwords to set / remove
#		                        .username - REQUIRED - Username
#		                        .password - OPTIONAL - Password to set or blank to remove
#		parameter_mailhog_auth_title      - OPTIONAL - Alternative descriptive title for actions taken
#
###
- name: "{{ parameter_add_bash_aliases_title | default('Setting up MailHog passwords') }} (Removing MailHog passwords)"
  lineinfile: dest="{{ role_package_mailhog__var__config_auth }}"
              regexp="^{{ item[1].username }}:"
              state=absent
  sudo: true
  with_indexed_items: parameter_mailhog_auth
  register: result_mailhog_passwords_removed
  until: not result_mailhog_passwords_removed.changed

- name: "{{ parameter_add_bash_aliases_title | default('Setting up MailHog passwords') }} (Encrypthing MailHog passwords)"
  shell: "{{ role_package_mailhog__var__bin }} bcrypt {{ item[1].password }}"
  sudo: true
  with_indexed_items: parameter_mailhog_auth
  register: result_mailhog_encripted_passwords
  when: item[1].password is defined and item[1].password != ''

- name: "{{ parameter_add_bash_aliases_title | default('Setting up MailHog passwords') }} (Adding MailHog passwords)"
  lineinfile: dest="{{ role_package_mailhog__var__config_auth }}"
              line="{{ item[1].username }}:{{ result_mailhog_encripted_passwords.results[item[0]].stdout }}"
              create=yes
  sudo: true
  with_indexed_items: parameter_mailhog_auth
  when: result_mailhog_encripted_passwords.results[item[0]].changed
