---
- include: ../../../../php5/operations_php5/tasks/php5_modules/install_php5_modules.yml
  vars:
    parameter_install_php5_modules_title: "Installing Php 5 modules for PhpMyAdmin"
    parameter_install_php5_modules: "{{ role_package_phpmyadmin__var__php5_modules_install }}"

- include: ../../../../php5/operations_php5/tasks/php5_modules/enable_php5_modules.yml
  vars:
    parameter_enable_php5_modules_title: "Enabling installed Php 5 modules for PhpMyAdmin"
    parameter_enable_php5_modules: "{{ role_package_phpmyadmin__var__php5_modules_install }}"

- include: ../../../../php5/operations_php5/tasks/php5_modules/enable_php5_modules.yml
  vars:
    parameter_enable_php5_modules_title: "Enabling additional Php 5 modules for PhpMyAdmin"
    parameter_enable_php5_modules: "{{ role_package_phpmyadmin__var__php5_modules_enable }}"
