###
# Manage Apt Packages
###
#
#	DESCRIPTION:
#
#		Manages specified Apt packages, installing them, updating them or removing them
#
###
#
#	VARIABLES:
#
#		parameter_manage_apt_packages                    - REQUIRED - List of packages to manage
#		parameter_manage_apt_packages_state              - REQUIRED - State of package (latest, absent, present, build-dep)
#		parameter_manage_apt_packages_prefix             - OPTIONAL - Prefix to apt packages names
#		parameter_manage_apt_packages_postfix            - OPTIONAL - Postfix to apt packages names
#		parameter_manage_apt_packages_title              - OPTIONAL - Alternative descriptive title of action taken
#		parameter_manage_apt_packages_force              - OPTIONAL - Should packages installation or removal be forced
#		parameter_manage_apt_packages_install_recommends - OPTIONAL - In case of installing packages should recommended packages be installed also
#		parameter_manage_apt_packages_purge              - OPTIONAL - In case of removing packages should configurations be removed as well
#		parameter_manage_apt_packages_notify             - OPTIONAL - Notification to trigger if changes have been made
#
###

- name: "{{ parameter_manage_apt_packages_title | default('Managing APT Packages') }}"
  apt: name="{{ parameter_manage_apt_packages_prefix | default('') }}{{ item[1] }}{{ parameter_manage_apt_packages_postfix | default('') }}"
       force="{{ parameter_manage_apt_packages_force | default( task_default__operations_apt__apt_packages__manage_apt_packages__force ) }}"
       install_recommends="{{ parameter_manage_apt_packages_install_recommends | default( task_default__operations_apt__apt_packages__manage_apt_packages__install_recommends ) }}"
       purge="{{ parameter_manage_apt_packages_purge | default( task_default__operations_apt__apt_packages__manage_apt_packages__purge ) }}"
       state="{{ parameter_manage_apt_packages_state | mandatory }}"
       update_cache=no
  sudo: true
  with_indexed_items: parameter_manage_apt_packages | mandatory
  notify: "{{ parameter_manage_apt_packages_notify | default('Dummy APT operation notification') }}"
